spring:
  datasource:                                             ## 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource              # 数据源 HikariCP
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动
    url: jdbc:mysql://192.168.8.116:3306/itzixi-pay?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username:
    password:
  redis:
    database: 0
    host:
    port:
    password:

