server:
  port: 8088

spring:
  datasource:
    # Mycat配置
    url: jdbc:mysql://192.168.8.116:8066/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: root
  redis:
  # Redis 单实例
    host: 192.168.8.116
    port: 6379
    password: redis
   # Redis 哨兵模式
#    database: 0
#    password: redis
#    sentinel:
#      master: mymaster
#      nodes: 192.168.8.116:26379, 192.168.8.117:26379, 192.168.8.118:26379
  # Redis 集群模式
#    password: redis
#    cluster:
#      nodes: 192.168.8.130:6379, 192.168.8.131:6379, 192.168.8.132:6379, 192.168.8.133:6379, 192.168.8.134:6379, 192.168.8.135:6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl